// Generated by CoffeeScript 1.7.1
var ApplicationLayout;

ApplicationLayout = Backbone.Marionette.Layout.extend({
  template: "#application-layout-template",
  regions: {
    createNodeMenu: "#add-note",
    desktopsMenu: "#desktops-menu",
    desktop: "#desktop"
  }
});
