// Generated by CoffeeScript 1.7.1
$(function() {
  var app;
  window.app = app = new Backbone.Marionette.Application();
  app.addInitializer(function(options) {
    this.collections = {};
    this.views = {};
    this.collections = {
      desktops: new DesktopsCollection(data.desktops),
      notes: new NotesCollection(data.notes)
    };
    this.desktopSubset = new Backbone.CollectionSubset({
      parent: this.collections.notes,
      filter: function() {
        return true;
      }
    });
    this.currentDesktop = new DesktopModel;
    this.stateCollections = {
      currentDesktopNotes: this.desktopSubset.child
    };
    return this.views = {
      desktop: new DesktopView({
        collection: this.stateCollections.currentDesktopNotes,
        el: '#desktop'
      }).render(),
      desktopsMenu: new DesktopsMenuView({
        collection: this.collections.desktops,
        currentDesktop: this.currentDesktop,
        el: '#desktops-menu'
      }).render(),
      createNote: new CreateNoteView({
        notesCollection: this.collections.notes,
        app: this,
        el: '#add-note'
      }).render()
    };
  });
  app.addInitializer(function(options) {
    var desktopsController;
    desktopsController = new DesktopsController({
      app: this,
      desktopSubset: this.desktopSubset,
      desktopCollection: this.collections.desktops,
      currentDesktopNotesCollection: this.stateCollections.currentDesktopNotes,
      notesCollection: this.collections.notes
    });
    new DesktopsRouter({
      controller: desktopsController
    });
    return Backbone.history.start();
  });
  return app.start();
});
