// Generated by CoffeeScript 1.7.1
var data;

data = {};

data.desktops = [
  {
    id: 1,
    title: 'Desktop 1'
  }, {
    id: 2,
    title: 'Desktop 2'
  }, {
    id: 3,
    title: 'Desktop 3'
  }
];

data.notes = [
  {
    id: 1,
    desktop_id: 1,
    type: 'text',
    text: 'text value'
  }, {
    id: 2,
    desktop_id: 1,
    type: 'image',
    url: 'http://froont.com'
  }, {
    id: 3,
    desktop_id: 2,
    type: 'text',
    text: 'text value 2'
  }, {
    id: 4,
    desktop_id: 2,
    type: 'image',
    url: 'http://froont.com/2'
  }
];
