// Generated by CoffeeScript 1.7.1
var Router;

Router = Backbone.Router.extend({
  routes: {
    '': 'desktop',
    'desktop/:id': 'desktop'
  },
  initialize: function(_arg) {
    this.desktopCollection = _arg.desktopCollection, this.notesCollection = _arg.notesCollection, this.currentDesktopNotesCollection = _arg.currentDesktopNotesCollection, this.currentDesktop = _arg.currentDesktop;
  },
  desktop: function(id) {
    var desktop;
    if (!id) {
      desktop = this.desktopCollection.at(0);
    } else {
      id = parseInt(id, 10);
      desktop = this.desktopCollection.get(id);
    }
    if (!desktop) {
      return;
    }
    this.currentDesktop = desktop;
    return this.currentDesktopNotesCollection.reset(this.notesCollection.where({
      desktop_id: id
    }));
  }
});
