// Generated by CoffeeScript 1.7.1
var Router;

Router = Backbone.Router.extend({
  routes: {
    '': 'desktop',
    'desktop/:id': 'desktop'
  },
  initialize: function(_arg) {
    this.desktopCollection = _arg.desktopCollection, this.notesCollection = _arg.notesCollection, this.currentDesktopNotesCollection = _arg.currentDesktopNotesCollection, this.currentDesktop = _arg.currentDesktop;
  },
  desktop: function(id) {
    var firstDesktop;
    if (!id) {
      firstDesktop = this.app.collections.desktops.at(0);
      if (!firstDesktop) {
        return;
      }
      id = firstDesktop.get('id');
    }
    id = parseInt(id, 10);
    return this.currentDesktopNotesCollection.reset(this.notesCollection.where({
      desktop_id: id
    }));
  }
});
