// Generated by CoffeeScript 1.7.1
var Router;

Router = Backbone.Router.extend({
  routes: {
    '': 'desktop',
    'desktop/:id': 'desktop'
  },
  initialize: function(options) {
    return this.app = options.app;
  },
  desktop: function(id) {
    var firstDesktop;
    if (!id) {
      firstDesktop = this.app.collections.desktops.at(0);
      if (!firstDesktop) {
        return;
      }
      id = firstDesktop.get('id');
    }
    return this.app.collections.currentDesktopNotes.reset(this.app.collections.notes.where({
      desktop_id: id
    }));
  }
});
