// Generated by CoffeeScript 1.7.1
var CreateNoteView;

CreateNoteView = Backbone.View.extend({
  template: Handlebars.compile($('#create-note-template').html()),
  events: {
    'click .text': 'addText',
    'click .image': 'addImage'
  },
  initialize: function(_arg) {
    this.notesCollection = _arg.notesCollection, this.currentDesktop = _arg.currentDesktop;
  },
  addText: function() {
    return this.notesCollection.create({
      type: 'text',
      desktop_id: this.currentDesktop.get('id')
    });
  },
  addImage: function() {
    return this.notesCollection.create({
      type: 'image',
      desktop_id: this.currentDesktop.get('id')
    });
  },
  render: function() {
    this.$el.html(this.template());
    return this;
  }
});
