// Generated by CoffeeScript 1.7.1
var DesktopsMenuView;

DesktopsMenuView = Backbone.Marionette.CollectionView.extend({
  tagName: 'ul',
  itemView: DesktopsMenuItemView,
  itemViewOptions: function() {
    return {
      currentDesktop: this.options.currentDesktop
    };
  }
});
