// Generated by CoffeeScript 1.7.1
var DesktopsMenuItemView;

DesktopsMenuItemView = Backbone.Marionette.ItemView.extend({
  tagName: 'li',
  template: Handlebars.compile($('#desktop-menu-item-template').html())
});
