// Generated by CoffeeScript 1.7.1
var DesktopsMenuItemView;

DesktopsMenuItemView = Backbone.Marionette.ItemView.extend({
  tagName: 'li',
  attributes: function() {
    if (this.model === this.options.currentDesktop) {
      return {
        "class": 'active'
      };
    }
  },
  template: Handlebars.compile($('#desktop-menu-item-template').html())
});
