// Generated by CoffeeScript 1.7.1
var DesktopView;

DesktopView = Backbone.Marionette.CollectionView.extend({
  tagName: 'ul',
  getItemView: function(item) {
    if (item.get('type') === 'image') {
      return ImageNoteView;
    }
    return TextNoteView;
  }
});
